#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-spec
Version  : 5.3.4
Release  : 4
URL      : https://rubygems.org/downloads/spec-5.3.4.gem
Source0  : https://rubygems.org/downloads/spec-5.3.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
#### spec [![Gem Version](https://badge.fury.io/rb/spec.png)](http://rubygems.org/gems/spec)[![Dependency Status](https://gemnasium.com/bootstraponline/spec.png)](https://gemnasium.com/bootstraponline/spec)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n spec-5.3.4
gem spec %{SOURCE0} -l --ruby > rubygem-spec.gemspec

%build
gem build rubygem-spec.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
spec-5.3.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/spec-5.3.4 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/spec-5.3.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/design_rationale.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/hoe/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/autorun.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/expectations.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/hell.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/parallel.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/pride.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/pride_plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/minitest/unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/lib/spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/readme.md
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/release_notes.md
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/spec.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/metametameta.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/test_minitest_benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/test_minitest_mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/test_minitest_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/test_minitest_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test/minitest/test_minitest_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test_custom/run.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test_custom/run_once_in_before_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/spec-5.3.4/test_custom/simple_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/spec-5.3.4.gemspec
