#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-spec
Version  : 5.3.4
Release  : 3
URL      : https://rubygems.org/downloads/spec-5.3.4.gem
Source0  : https://rubygems.org/downloads/spec-5.3.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
#### spec [![Gem Version](https://badge.fury.io/rb/spec.png)](http://rubygems.org/gems/spec)[![Dependency Status](https://gemnasium.com/bootstraponline/spec.png)](https://gemnasium.com/bootstraponline/spec)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n spec-5.3.4
gem spec %{SOURCE0} -l --ruby > rubygem-spec.gemspec

%build
gem build rubygem-spec.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
spec-5.3.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/spec-5.3.4 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/spec-5.3.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Hoe/Minitest/cdesc-Minitest.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Hoe/cdesc-Hoe.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/AbstractReporter/cdesc-AbstractReporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/AbstractReporter/passed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/AbstractReporter/record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/AbstractReporter/report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/AbstractReporter/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertion/cdesc-Assertion.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertion/location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_in_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_in_epsilon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_includes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_instance_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_kind_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_operator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_predicate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_raises-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_respond_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_same-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_send-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_silent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/assert_throws-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/capture_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/capture_subprocess_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/diff%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/diff-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/exception_details-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/flunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/mu_pp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/mu_pp_for_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/pass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_in_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_in_epsilon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_includes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_instance_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_kind_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_operator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_predicate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_respond_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/refute_same-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Assertions/skipped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BacktraceFilter/cdesc-BacktraceFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/bench-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/bench_performance_constant-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/bench_performance_exponential-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/bench_performance_linear-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/bench_range-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/BenchSpec/cdesc-BenchSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance_constant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance_exponential-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance_linear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance_logarithmic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/assert_performance_power-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/bench_exp-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/bench_linear-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/bench_range-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/cdesc-Benchmark.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/fit_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/fit_exponential-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/fit_linear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/fit_logarithmic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/fit_power-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/sigma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Benchmark/validation_for_fit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/CompositeReporter/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/CompositeReporter/cdesc-CompositeReporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/CompositeReporter/reporters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/cdesc-Expectations.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_close_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_instance_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_kind_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_same_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_silent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_within_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_be_within_epsilon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_raise-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_respond_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/must_throw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_close_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_instance_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_kind_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_same_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_within_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_be_within_epsilon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Expectations/wont_respond_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/cdesc-Guard.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/jruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/maglev%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/mri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/rubinius%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Guard/windows%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Mock/cdesc-Mock.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Mock/expect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Mock/verify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Executor/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Executor/cdesc-Executor.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Executor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Executor/shutdown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Executor/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Test/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Test/ClassMethods/run_one_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Test/ClassMethods/test_order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Test/_synchronize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Parallel/cdesc-Parallel.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/cdesc-PrideIO.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/pride%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/pride%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/pride-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideIO/print-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideLOL/cdesc-PrideLOL.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/PrideLOL/pride-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/ProgressReporter/cdesc-ProgressReporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Reporter/cdesc-Reporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/assertions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/cdesc-Runnable.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/failures-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/methods_matching-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/name%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/passed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/result_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/run_one_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/runnable_methods-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/runnables-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Runnable/skipped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Skip/cdesc-Skip.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/after-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/it-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/let-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/register_spec_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/spec_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/subject-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/DSL/t-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Spec/cdesc-Spec.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/StatisticsReporter/cdesc-StatisticsReporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/SummaryReporter/cdesc-SummaryReporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/after_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/after_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/before_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/before_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/cdesc-LifecycleHooks.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/LifecycleHooks/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/error%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/i_suck_and_my_tests_are_order_dependent%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/io_lock-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/make_my_diffs_pretty%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/old_test_order-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/parallelize_me%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/passed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/result_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/runnable_methods-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/skipped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/test_order-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Test/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/UnexpectedError/cdesc-UnexpectedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Unit/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/__run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/after_run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/autorun-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/cdesc-Minitest.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/on_exit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/run_specs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/trace_specs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Minitest/unknown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/MockExpectationError/cdesc-MockExpectationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/page-History_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/spec-5.3.4/ri/page-README_txt.ri
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/design_rationale.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/hoe/minitest.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/autorun.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/expectations.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/hell.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/mock.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/parallel.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/pride.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/pride_plugin.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/test.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/minitest/unit.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/lib/spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/readme.md
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/release_notes.md
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/spec.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/metametameta.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/test_minitest_benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/test_minitest_mock.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/test_minitest_reporter.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/test_minitest_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test/minitest/test_minitest_unit.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test_custom/run.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test_custom/run_once_in_before_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/spec-5.3.4/test_custom/simple_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/spec-5.3.4.gemspec
